### ISSUE TITLE
Execution failed for task ':react-native-iap:compilePlayDebugKotlin' on React Native 0.71.5

### ISSUE THREAD

**Issue by ShivamJoker** [dooboolab-community/react-native-iap#2396]
**Description**

I am unable to get the iap module work with the latest react native, I even tried the next version on rn-iap, I kept getting the same error.

**Error**

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-iap:compilePlayDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 12s

    at makeError (/home/shivam/ReactNative/SqlPlay/node_modules/execa/index.js:174:9)
    at /home/shivam/ReactNative/SqlPlay/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/home/shivam/ReactNative/SqlPlay/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:82:7)
    at async Command.handleAction (/home/shivam/ReactNative/SqlPlay/node_modules/@react-native-community/cli/build/index.js:108:9)
```

**Config**

```gradle
buildscript {
    ext {
        kotlinVersion = '1.8.10'
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
}
```

**Comment by ShivamJoker** [comment]
Even when linking package manually it seems to give the same error

**Comment by andresesfm** [comment]
> Compilation error. See log for more details
Can you include the actual errors in the logs?

**Comment by ShivamJoker** [comment]
I am not sure what was the issue but somehow when I installed the library again with the latest kotlin version it seems to work.
