### ISSUE TITLE
[Android crash] java.lang.SecurityException - Not allowed to bind to service Intent

### ISSUE THREAD

**Issue by haozhutw** [dooboolab-community/react-native-iap#2838]
> Please use the [Discussion board](https://github.com/dooboolab-community/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

Android app crashes

**Expected Behavior**

App shouldn't crash

**Screenshots**

<img width="1230" alt="image" src="https://github.com/user-attachments/assets/dddefa10-1083-4075-a1e8-2622b3fcd43e">

<img width="1249" alt="image" src="https://github.com/user-attachments/assets/76e24da1-adfa-496b-b859-423b7fe101d1">

**Environment:**

- react-native-iap: 12.15.1
- react-native: 0.61.5
- Platforms (iOS, Android, emulator, simulator, device): Android

**To Reproduce**

We cannot reproduce this, this crash is reported by Firebase.

---

[Optional] **Additional Context**

crash log:

```
Fatal Exception: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.android.vending.billing.InAppBillingService.BIND pkg=com.android.vending cmp=com.android.vending/com.google.android.finsky.billing.iab.InAppBillingService (has extras) }
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1838)
       at android.app.ContextImpl.bindService(ContextImpl.java:1749)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:756)
       at com.android.billingclient.api.BillingClientImpl.startConnection(com.android.billingclient:billing@@7.0.0:62)
       at com.dooboolab.rniap.RNIapModule.initConnection(RNIapModule.kt:150)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
       at android.os.Looper.loop(Looper.java:223)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
       at java.lang.Thread.run(Thread.java:923)
        
```

**Comment by hyochan** [comment]
I’m closing all issues reported in versions below 14, as the library now supports the new architecture with NitroModules and has been completely revamped.
